<a href="https://colab.research.google.com/github/sohdacafe/cheat_sheet/blob/main/numpy_cheat_sheet_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [31]:
# ベクトルの定義
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
np.array(range(1,4))

array([1, 2, 3])

In [15]:
# 行列の定義
A = np.array([[1,2,3], [4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
A.shape

(2, 3)

In [32]:
A.ndim

2

In [10]:
B = np.array([[1,2], [3,4], [5,6]])
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
B.shape

(3, 2)

In [17]:
A.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
np.append(B, [[7,8]], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [23]:
np.append(B, [[7],[8],[9]], axis=1)

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

In [24]:
B[0]

array([1, 2])

In [25]:
B[0][1]

2

In [26]:
B+2

array([[3, 4],
       [5, 6],
       [7, 8]])

In [28]:
B*3

array([[ 3,  6],
       [ 9, 12],
       [15, 18]])

In [30]:
np.dot(A,B)

array([[22, 28],
       [49, 64]])

In [38]:
# 0~1の一様分布に従う乱数
np.random.rand(3,2)

array([[0.8266832 , 0.87274788],
       [0.54215378, 0.02442694],
       [0.23177623, 0.57730968]])

In [37]:
# 標準正規分布に従う乱数
np.random.randn(3,2)

array([[ 0.9900925 , -1.37656336],
       [ 1.44495755,  0.25782416],
       [-0.47713527,  0.08020616]])

In [42]:
b = np.array([1,2,3,4,5])

In [43]:
np.sum(b)

15

In [46]:
np.mean(b), np.std(b)

(3.0, 1.4142135623730951)

In [45]:
np.max(b), np.min(b)

(5, 1)

In [47]:
np.mean(B, axis=0)

array([3., 4.])